### ISSUE TITLE
Configurations Env File

### ISSUE THREAD

**Issue by mario-oberwalder** [Gepardec/GranitTreff-030620#3]
A template .env file would be great. 
What are the default values for JENKINS_PORT, NEXUS_PORT and the KUBERNETES_URL?

**Comment by cchet** [comment]
There are no default values, you need to define them. 
The ports are the binding ports from the Docker Containers to the host (see docker/docker-compose.yml) and are also used by the Jenkins configuration. The Kubernetes url tells Jenkins where to find the Kubernetes cluster.

**Comment by mario-oberwalder** [comment]
What would be good ports to use? Are 8083 for jenkins and 8081 for nexus okay?

**Comment by cchet** [comment]
It does not matter, they just need to be different from each other. Usually, someone would choose ports in the range of 8080 - 8100 or 9080 - 9100 for such a purpose. This depends if you have other stuff running on the standard used unprivileged ports.

**Comment by mario-oberwalder** [comment]
Great, thank you.
